name: release
on:
  push:
  pull_request:
    branches: [github-actions]
jobs:
  build:
    matrix:
      os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install Just
        uses: extractions/setup-just@v1
      - name: Build
        run: cd crystal && just build
