on:
  push:
  pull_request:
    branches: [github-actions]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
      - name: Install Just
        uses: extractions/setup-just@v1
      - name: Run tests
        run: cd crystal && just build
